Admin rights to delete simulations
cyberbotics/webots-cloud pull request #18
Opened 2022-05-02 10:18 UTC by ThomasOliverKimble

Added admin rights to delete simulations.
Other minor style mods and cleanup.

2022-05-02 11:46 UTC, omichel requested changes

2022-05-02 11:46 UTC, omichel commented on httpdocs/js/webots-cloud.js
> +            }
```suggestion
            else if (data.status == 1)
              project.load(`/simulation${(page > 1) ? ('?p=' + page) : ''}`);
```

2022-05-02 11:46 UTC, omichel commented on httpdocs/js/webots-cloud.js
> +      const delete_project = admin ? `<td class="has-text-centered">${delete_icon}</td>` : ``;
It seems the corresponding `<th>` would be missing here. Even, if empty, we should probably add it so that resulting HTML is conform.
If I type:
```html
<!DOCTYPE html>
<html lang="en">
<head><title>Title></title></head>
<body>
<table>
<thead><tr><th>1</th><th>2</th></tr></thead>
<tbody>
<tr><td>1</td></tr>
</tbody>
</table>
</body>
</html>
```
In the [HTML5 validator](https://validator.w3.org), I am getting:
```
Warning: A table row was 1 columns wide, which is less than the column count established by the first row (2).
```

2022-05-02 11:46 UTC, omichel commented on httpdocs/ajax/project/delete.php
> +die("{\"status\":1}");
```suggestion
die('{"status":1}');
```

2022-05-02 11:46 UTC, omichel commented on httpdocs/ajax/project/delete.php
> +  error('Could not delete simulation');
We generally use double quote for English messages as they may often contain single quotes:
```suggestion
  error("Could not delete simulation");
```

2022-05-03 10:01 UTC, ThomasOliverKimble commented on httpdocs/js/webots-cloud.js
> +      const delete_project = admin ? `<td class="has-text-centered">${delete_icon}</td>` : ``;
In `webots-cloud.js` lines 310 to 317 we can see that there is already an extra `<th>` there. I decided to use the empty one that was already there.

```html
<tr>
  <th style="text-align:center" title="Number of GitHub stars"><i class="far fa-star"></i></th>
  <th title="Title of the simulation">Title</th>
  <th title="Version of the simulation">Version</th>
  <th title="Type of simulation">Type</th>
  <th title="Last update time">Updated</th>
  <th colspan="1"></th>
</tr>
```

2022-05-03 10:08 UTC, omichel commented on httpdocs/js/webots-cloud.js
> +      const delete_project = admin ? `<td class="has-text-centered">${delete_icon}</td>` : ``;
OK, so in that case, we should probably add an empty `<td></td>` if not admin to match the extra `<th></th>`, and I guess we could remove the `colspan="1"` which seems useless.

2022-05-03 10:10 UTC, omichel commented on httpdocs/js/webots-cloud.js
> +      const delete_project = admin ? `<td class="has-text-centered">${delete_icon}</td>` : ``;
```suggestion
      const delete_icon = admin ? `<i style="color: red" class="is-clickable far fa-trash-alt fa-sm" id="delete-${data.id}" title="Delete ${data.type} as administrator"></i>`: ``;
```

2022-05-03 10:11 UTC, omichel commented on httpdocs/js/webots-cloud.js
> +        `${delete_project}`;
```suggestion
        `<td class="has-text-right is-size-7" title="Last synchronization with GitHub">${updated}</td>` + 
        `<td class="has-text-centered">${delete_icon}</td>`;
```

2022-05-04 07:53 UTC, ThomasOliverKimble commented on httpdocs/js/webots-cloud.js
> +      const delete_project = admin ? `<td class="has-text-centered">${delete_icon}</td>` : ``;
I have decided to go with the inverse solution:
* Without admin rights: removed the useless `<th></th>` from the table and `delete_project` stays empty
* With admin rights: added a blank `<th></th>` (lines 635-636) to the table and `delete_project` contains the trash icon in a new `<td></td>`

This stays consistent with _scenes_ and _animations_: not having an extra empty `<th></th>` at the end of the table.

2022-05-04 08:05 UTC, omichel submitted a review, later dismissed
Thank you.

2022-05-04 08:05 UTC, omichel commented on httpdocs/js/webots-cloud.js
> +            if (project.email ? project.email.endsWith('@cyberbotics.com') : false)
That works but is little bit odd, we are more used to this form:
```suggestion
            if (project.email && project.email.endsWith('@cyberbotics.com'))
```

2022-05-04 08:14 UTC, omichel commented on httpdocs/js/webots-cloud.js
> +      const delete_project = admin ? `<td class="has-text-centered">${delete_icon}</td>` : ``;
That's indeed better.

2022-05-04 08:23 UTC, omichel approved these changes
Thank you.

2022-05-04 08:48 UTC, merged